version: '3'

services: 
    web:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        ports: 
            - 8000:8000
        volumes: 
            - .:/src/app
        depends_on:
            - pgdb

    pgdb:
        image: postgres
        container_name: pgdb
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_ROOT_PASSWORD: postgres
        volumes:
            - .:/app/src/mysqld
            - ./db:/app/src/mysql
